export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN'

export const REQUEST_USER_INFO = 'REQUEST_USER_INFO'
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO'

export const REQUEST_DASHBOARD = 'REQUEST_DASHBOARD'
export const RECEIVE_DASHBOARD = 'RECEIVE_DASHBOARD'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const LOGOUT = 'LOGOUT'

export const REQUEST_LOGIN_ELE = 'REQUEST_LOGIN_ELE'
export const RECEIVE_LOGIN_ELE = 'RECEIVE_LOGIN_ELE'
export const REQUEST_ELE_SMS_CODE = 'REQUEST_ELE_SMS_CODE'
export const RECEIVE_ELE_SMS_CODE = 'RECEIVE_ELE_SMS_CODE'
export const REQUEST_ELE_PIC_CODE = 'REQUEST_ELE_PIC_CODE'
export const RECEIVE_ELE_PIC_CODE = 'RECEIVE_ELE_PIC_CODE'

export const REQUEST_CRAWLER_CONFIG = 'REQUEST_CRAWLER_CONFIG'
export const RECEIVE_CRAWLER_CONFIG = 'RECEIVE_CRAWLER_CONFIG'

export const REQUEST_ELE_CITY_LIST = 'REQUEST_ELE_CITY_LIST'
export const RECEIVE_ELE_CITY_LIST = 'RECEIVE_ELE_CITY_LIST'
export const REQUEST_SEARCH_ELE_ADDRESS = 'REQUEST_SEARCH_ELE_ADDRESS'
export const RECEIVE_SEARCH_ELE_ADDRESS = 'RECEIVE_SEARCH_ELE_ADDRESS'

export const REQUEST_ELE_RESTAURANTS = 'REQUEST_ELE_RESTAURANTS'
export const RECEIVE_ELE_RESTAURANTS = 'RECEIVE_ELE_RESTAURANTS'

export const REQUEST_SIGNUP = 'REQUEST_SIGNUP'
export const RECEIVE_SIGNUP = 'RECEIVE_SIGNUP'

export const REQUEST_CRAWLER_TASKS = 'REQUEST_CRAWLER_TASKS'
export const RECEIVE_CRAWLER_TASKS = 'RECEIVE_CRAWLER_TASKS'